---
title: "Workshop Facilitator Training"
author: "Jasmine Lai and Yuka Takemon"
format: gfm
editor: visual
toc: true
---

Thank you for agreeing to teach with us this year! This document will go through what the day will look like!

### Day of the workshop

-   There will be at least one organizer on hand to help assist
-   There will also be volunteers around at each workshop. If you have any specific requests please let us know. ***If you would like to bring people you know please have them fill in the volunteer form so we can add them to the attendance list***. They will need to be on the list to have access to the building.

#### Schedule

A detail rundown of the day can be found here: [Run of Show](https://docs.google.com/spreadsheets/d/1oMnrFFCDtJDw949xNyk6ixb7r6xHqqpLnzMEULuNy7A/edit#gid=0). Please note that it is a document that we are working actively on updating so things might change before the event.

One of the organizing committee members will be around 30 minutes before the start of workshop so please feel free to arrive early to get setup.

#### Code of Conduct

**Pre-workshop:** Please review our [code of conduct](https://docs.google.com/document/d/182aSWdbPO3QNWJ_mkKtRIUTBkmwRug8t/edit?usp=sharing&ouid=108757651896532540288&rtpof=true&sd=true). We also have a [form](https://forms.gle/GhhssDKqU55We33w8) for you and the participants to report any incidents.

**On the day of your workshop:** Our committee will be on site and in class rooms to help resolve any issues that may arise. We also will have a few external code of conduct violation reviewers that can address any issues that may be related participants as well as any of the committee members. These are third party members will you your advocate and are at arm's length of all committee members.

A committee member will introduce you as well as our code of conduct using this short [presentation](https://docs.google.com/presentation/d/18e8xvcegwKsowc3sqTGIB2L5XqMSUHEpVuMrUncsrO4) to participants before the workshop begins. Please have this link to the code of conduct presentation handy on the day.

### Facilitating Inclusive Collaborations with Computational and Data-Intensive Research

**September 26, 6:00 PM to 8:00 PM (PST) on Zoom**

We highly recommended all instructors, new and seasoned, to participate in Kate Hertweck's workshop! [Sign up here](https://docs.google.com/forms/d/e/1FAIpQLSeaaGUrtPKYdtkC3wsxc4eD5k1y-olhyocjjam1diOJtzIL5w/viewform)

**Workshop description**: Perhaps the biggest challenge faced by experts in data and computational research is communicating effectively with colleagues and team members with different areas of expertise. This workshop will explore why interdisciplinary collaboration is so difficult, and help you develop strategies for building inclusive, cooperative work with diverse teams.

**About Kate Hertweck:** Kate Hertweck is a scientist and educator who cares about community, collaboration, and equitable access to scientific knowledge. Kate's research background is in evolutionary biology, and they have worked on areas ranging from genomic evolution in plants to cancer transcriptomics. Kate spent time as a faculty member before transitioning to research support, and now works as a program manager for the Open Science program at Chan Zuckerberg Initiative.

------------------------------------------------------------------------

### Information for in-person workshops

#### Location

Northeastern University - Vancouver Campus

> 410 W Georgia St #1400, Vancouver, BC V6B 1Z3

-   We will provide the participant list to Northeastern. Please tell the security that you are here for the Datajam event and your name and they will call the elevator.

#### Parking

Secure parking is available in the underground parkade, accessible from the laneway on the west side of the building. The parking facility will have meters to purchase parking, at the following rates (plus applicable taxes):

-   \$3 per half hour
-   \$6 per hour
-   \$18 All Day until 6pm
-   \$10 Evening, 6pm to Close

Outdoor public bike parking is currently available across the street at the Vancouver Public Library.

## Day of Contact

Call or text Jasmine at (604) 802-1677 if there are any issues!
